---
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'site/**'
    branches:
      - master

jobs:
  build:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: site
      - name: Build website
        run: yarn build
        working-directory: site
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
